version: '3.8'
services:
  web:
    container_name: sonarqube-service
    privileged: true
    build:
      context: .
    ports:
      - "9000:9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
